In [1]:
import tensorflow as tf

In [2]:
tf.enable_eager_execution()
print(tf.add(1, 2))

tf.Tensor(3, shape=(), dtype=int32)


In [3]:
x = tf.random_uniform([3, 3])

print("Is there a GPU available: "),
print(tf.test.is_gpu_available())

print("Is the Tensor on GPU #0:  "),
print(x.device.endswith('GPU:0'))

Is there a GPU available: 
False
Is the Tensor on GPU #0:  
False


In [4]:
import numpy as np 
ndarray = np.ones([3,3])

In [5]:
ndarray

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
tensor = tf.multiply(ndarray, 42)

In [7]:
tensor.numpy()

array([[42., 42., 42.],
       [42., 42., 42.],
       [42., 42., 42.]])

In [8]:
tensor.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [9]:
x = tf.ones((2,2))

In [10]:
x

<tf.Tensor: id=17, shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [11]:
with tf.GradientTape() as tape:
    tape.watch(x)
    y = tf.reduce_sum(x)
    z = tf.multiply(y,y)


In [12]:
dz_dx = tape.gradient(z, x)

In [13]:
for i in [0, 1]:
    for j in [0, 1]:
        assert dz_dx[i][j].numpy() == 8